variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2 -Dmaven.artifact.threads=8"

stages:
  - test
  - deploy

test:
  stage: test
  image: postgres
  script:
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB"
#    - mvn -q clean
#    - mvn -q package
#  cache:
#    paths:
#      - .m2/
  artifacts:
    paths:
      - target/crm-service-1.0.0-SNAPSHOT.jar

deploy:
  stage: deploy
  image: ruby:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master